### ISSUE TITLE
Getting an error while accessing ember table crossover two routes

### ISSUE THREAD

**Issue by chandruaskutty** [intuitivepixel/ember-cli-ember-table#12]
Hi , 

I am using ember cli table on two different routes , I am getting an error while traversing across both route that " Uncaught TypeError: Cannot read property 'get' of undefined"  on the line of " return row.get('content'); "

Regards,
Chandra sekar.

**Comment by intuitivepixel** [comment]
This question is better suited for StackOverflow i think, closing.
