### ISSUE TITLE
Small issue using Ember Canary and Handlebars 2.0

### ISSUE THREAD

**Issue by pete-the-pete** [intuitivepixel/ember-cli-ember-table#13]
I found your addon through Addepar/ember-table/issues/227. I started using your addon and got it working, which is super exciting.  I had an issue with something being undefined and came up with the following patch/short term fix.

Using your example code, I got the following error on an AttrNode.
![screen shot 2015-03-04 at 1 26 26 pm](https://cloud.githubusercontent.com/assets/345985/6494480/f4c878be-c276-11e4-8173-17f301ee16b1.png)
![screen shot 2015-03-04 at 2 01 34 pm](https://cloud.githubusercontent.com/assets/345985/6494484/00917394-c277-11e4-9bc5-e91fddb22f6f.png)

I made this change: 0d357257238c5c5653a65e3fbf05213a7696934b, and now it works great!

Thanks,
  Pete

**Comment by intuitivepixel** [comment]
Closing, please follow along Addepar/ember-table#227, The Author is making the effort to port the original project to ember-cli, so stay tuned

**Comment by pete-the-pete** [comment]
Ya, looking forward to it!
