### ISSUE TITLE
Can't import column-definitions class

### ISSUE THREAD

**Issue by tolgaek** [intuitivepixel/ember-cli-ember-table#16]
I'm using ember-cli 0.2.0 and I followed the steps and I can access ember-table but I can't import column definitions to define columns.

I tried `import ColumnDefinition from '../column-definition';` from the README but this check is relative to my controller which doesn't have that class

**Comment by intuitivepixel** [comment]
Closing, please follow along Addepar/ember-table#227, The Author is making the effort to port the original project to ember-cli, so stay tuned

**Comment by tolgaek** [comment]
@intuitivepixel His last suggestion seems to suggest that we continue using your library. I really wanted to use this in my project if I could just get over the ColumnDefinition issue. Is there a way to fix this?

**Comment by tolgaek** [comment]
Resolved, this was due to nested structure of my controllers. So using `import ColumnDefinition from '../../column-definition';` fixed the issue

**Comment by intuitivepixel** [comment]
oh glad to hear!
