### ISSUE TITLE
Does not compile properly in production mode

### ISSUE THREAD

**Issue by alexspeller** [intuitivepixel/ember-cli-ember-table#2]
`ember serve --environment=production` causes an error on page load:

```
Error while processing route: index Could not find module ember-cli-ember-table/column-definition Error: Could not find module ember-cli-ember-table/column-definition
```
I think it has something to do with the module being compiled to this:
```
define("myapp/column-definition",["ember-cli-ember-table/column-definition","exports"]
```

**Comment by intuitivepixel** [comment]
Closing, please follow along Addepar/ember-table#227, The Author is making the effort to port the original project to ember-cli, so stay tuned
