### ISSUE TITLE
doesn't render w/ default cell classes

### ISSUE THREAD

**Issue by shaunc** [intuitivepixel/ember-cli-ember-table#4]
With a default column definition:

          ColumnDefinition.create
            columnWidth: 200
            textAlign: 'text-align-left'
            headerCellName: @get('model.name')
            getCellContent: (row)->
              row.get('content.name')]

I got an error in MultiItemViewCollectionView, probably due to the inability to resolve global reference to Ember.Table.HeaderCell & TableCell.

When I explicitly specified the classes I could render:

    `import HeaderCell from 'ember-cli-ember-table/views/header-cell'`
    `import TableCell from 'ember-cli-ember-table/views/table-cell'`
    ...
          ColumnDefinition.create
            columnWidth: 200
            textAlign: 'text-align-left'
            headerCellName: @get('model.name')
            headerCellViewClass: HeaderCell
            tableCellViewClass: TableCell
            getCellContent: (row)->
              row.get('content.name')]

**Comment by intuitivepixel** [comment]
Closing, please follow along Addepar/ember-table#227, The Author is making the effort to port the original project to ember-cli, so stay tuned
