### ISSUE TITLE
Error when upgrade to ember 1.9 and handlebar 2.0

### ISSUE THREAD

**Issue by songzijun** [intuitivepixel/ember-cli-ember-table#6]
I am getting the following errors when upgrade ember and handlebar. 

Uncaught Error: Unknown template object: function
Uncaught Error: Could not find module ember-cli-ember-table/components/ember-table

**Comment by intuitivepixel** [comment]
Closing, please follow along https://github.com/Addepar/ember-table/issues/227, The Author is making the effort to port the original project to ember-cli, so stay tuned
