### ISSUE TITLE
Table not rendering before scrolling again

### ISSUE THREAD

**Issue by chandruaskutty** [intuitivepixel/ember-cli-ember-table#7]
@intuitivepixel @alexspeller I found the same issue on my project but the fix was there on mentioned file . I hope your workaround is temporary when I changed the initial scroll 30 to 180 that is works fine for me. I guess initial scroll top value depends upon the table height.

```  
// Workaround to fix #1
  fixBlankOnLoad: function () {
    Ember.run.next(this, function() {
      this.set('scrollTop', 30);
      Ember.run.next(this, function() {
        this.set('scrollTop', 0);
      });
    });
  }.on('didInsertElement'),
```
Here is my workaround. I trust this will work better in all table height.
```  
 fixBlankOnLoad: function () {
    Ember.run.next(this, function() {
      this.set('scrollTop', this.get('_parentView.height')/10);
      Ember.run.next(this, function() {
        this.set('scrollTop', 0);
      });
    });
  }.on('didInsertElement'),
```

**Comment by intuitivepixel** [comment]
Closing, please follow along Addepar/ember-table#227, The Author is making the effort to port the original project to ember-cli, so stay tuned
