### ISSUE TITLE
horizontal scroll problems...

### ISSUE THREAD

**Issue by shaunc** [intuitivepixel/ember-cli-ember-table#8]
I used ember-cli-ember-table before in other contexts successfully, but just built a table with many columns, and found that the columns wrapped -- cells from one row would appear in the next; also no horizontal scroll bar appears.

I have created a test app at [shaunc/test-table](https://github.com/shaunc/test-table).

I'm sure there is some misconfiguration somewhere, but I'm not seeing it -- a solution or any debugging pointers would be welcome.

Thanks! -- Shaun

**Comment by shaunc** [comment]
A picture of what is happening...
![image](https://cloud.githubusercontent.com/assets/193170/5749725/b6f560a2-9c19-11e4-898f-bac12db62ea6.png)

**Comment by shaunc** [comment]
When I specify "columnWidth" in the ColumnDefinition options, the problem goes away. Hmm... does this have to do with the specific version of ember-table the project is using? ... I thought the width would be calculated automatically if not specified.

**Comment by intuitivepixel** [comment]
Closing, please follow along Addepar/ember-table#227, The Author is making the effort to port the original project to ember-cli, so stay tuned
